### ISSUE TITLE
Module prevents start up of on enterprise mendix server

### ISSUE THREAD

**Issue by Mocke44** [mendix/MxPushNotifications#58]
Hi,

I am attempting to deploy an app (mx 7.5.1) which implements the push notifications module.
When attempting to start the app for the first time, i get an error executing DDL commands when trying to sync the database which prevents the app from starting.
The error is for an index on pushNotifications.$Device/RegistrationID. I do not know what this index is used for and I am hesitant to remove it.
Is this a known issue? is there a work around?
Please see the below full stack trace for more information.
An error occurred while executing action 'Execute DDL commands'.

--------

com.mendix.m2ee.api.AdminException: Executing DDL commands for component MyFirstComponent failed.
	at com.mendix.basis.component.internal.LocalComponentImpl.executeDDLCommands(LocalComponentImpl.scala:117)

Caused by: com.mendix.basis.connectionbus.ConnectionBusException: Error (SQL State: S0001, Error Code: 1919) on executing:

CREATE INDEX [idx_pushnotifications$device_registrationid] ON [pushnotifications$device] ([registrationid],[id])

All changes are rolled back.
	at com.mendix.connectionbus.modelsynchronization.DdlCommandExecutor.execute(DdlCommandExecutor.java:77)

Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Column 'registrationid' in table 'pushnotifications$device' is of a type that is invalid for use as a key column in an index.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:232)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1672)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:903)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:796)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7535)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2438)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:208)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:183)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.execute(SQLServerStatement.java:769)
	at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:291)
	at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:291)
	at com.mendix.connectionbus.modelsynchronization.DdlCommandExecutor.executeDdlCommands(DdlCommandExecutor.java:134)
	at com.mendix.connectionbus.modelsynchronization.DdlCommandExecutor.execute(DdlCommandExecutor.java:41)
	at com.mendix.connectionbus.modelsynchronization.SynchronizationManager.synchronizeModel(SynchronizationManager.scala:154)
	at com.mendix.connectionbus.modelsynchronization.SynchronizationManager.executeImpl(SynchronizationManager.scala:145)
	at com.mendix.connectionbus.modelsynchronization.SynchronizationManager.execute(SynchronizationManager.scala:93)
	at com.mendix.connectionbus.ConnectionBusImpl.executeDDLCommands(ConnectionBusImpl.java:408)
	at com.mendix.basis.component.internal.LocalComponentImpl.executeDDLCommands(LocalComponentImpl.scala:113)
	at com.mendix.basis.impl.MxRuntimeImpl.executeDDLCommands(MxRuntimeImpl.java:989)
	at com.mendix.basis.action.admin.ExecuteDDLCommandsAction.call(ExecuteDDLCommandsAction.java:27)
	at com.mendix.basis.action.admin.RuntimeAdminAction.execute(RuntimeAdminAction.java:18)
	at com.mendix.m2ee.appcontainer.server.handler.HttpAdminHandler.handle(HttpAdminHandler.java:122)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:368)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:942)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1004)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:647)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:628)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Unknown Source)

**Comment by KevinVlaanderen** [comment]
Hi,

We just published a new version of the PushNotifications connector in the appstore (version 2.3.2). In this version, we reduced the size of the RegistrationID to 255 chars, which should be enough in all cases. Previously, it was 4096, to deal with the size GCM registration IDs being unspecified. Microsoft SQL server cannot handle indices of that size (limit of 900 bytes).

https://appstore.home.mendix.com/link/app/3003/

Could you please verify that this solves your issue?

Cheers,
Kevin

**Comment by Mocke44** [comment]
Hi,

Sorry i did not see this until now, apologies. Yes this fixed solved my issue, thanks
