### ISSUE TITLE
Error in after startup action

### ISSUE THREAD

**Issue by RCatersels** [mendix/MxPushNotifications#60]
When updating the MxPushnotification to the latest version I now have an after startup error.
I already found this post: https://forum.mendixcloud.com/link/questions/85945
Will check if this solves the issue.
Regards,
Ronald

Uncaught error from thread [MxRuntimeSystem-action-dispatcher-28]: loader constraint violation: when resolving method "org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;" the class loader (instance of org/apache/felix/framework/BundleWiringImpl$BundleClassLoaderJava5) of the current class, org/slf4j/LoggerFactory, and the class loader (instance of org/apache/felix/framework/BundleWiringImpl$BundleClassLoaderJava5) for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature, shutting down ActorSystem[MxRuntimeSystem]

--------

java.lang.LinkageError: loader constraint violation: when resolving method "org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;" the class loader (instance of org/apache/felix/framework/BundleWiringImpl$BundleClassLoaderJava5) of the current class, org/slf4j/LoggerFactory, and the class loader (instance of org/apache/felix/framework/BundleWiringImpl$BundleClassLoaderJava5) for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:418)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
	at org.opensaml.DefaultBootstrap.getLogger(DefaultBootstrap.java:221)
	at org.opensaml.DefaultBootstrap.initializeXMLSecurity(DefaultBootstrap.java:151)
	at org.opensaml.DefaultBootstrap.bootstrap(DefaultBootstrap.java:87)
	at saml20.implementation.SAMLRequestHandler.<init>(SAMLRequestHandler.java:65)
	at saml20.implementation.SAMLRequestHandler.getInstance(SAMLRequestHandler.java:59)
	at saml20.implementation.SSOServerConfiguration.start(SSOServerConfiguration.java:18)
	at saml20.actions.StartSSO.executeAction(StartSSO.java:27)
	at saml20.actions.StartSSO.executeAction(StartSSO.java:16)
	at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:49)
	at com.mendix.core.actionmanagement.CoreAction.doCall(CoreAction.java:260)
	at com.mendix.core.actionmanagement.CoreAction.call(CoreAction.java:248)
	at com.mendix.core.actionmanagement.ActionManager$1.execute(ActionManager.java:168)
	at com.mendix.util.classloading.Runner.doRunUsingClassLoaderOf(Runner.java:36)
	at com.mendix.core.actionmanagement.ActionManager.executeSync(ActionManager.java:172)
	at com.mendix.core.component.InternalCore.execute(InternalCore.java:496)
	at com.mendix.modules.microflowengine.actions.actioncall.JavaAction.execute(JavaAction.scala:52)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowObject.execute(MicroflowObject.java:47)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.executeAfterBreakingIfNecessary(MicroflowImpl.java:192)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.executeAction(MicroflowImpl.java:149)
	at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:49)
	at com.mendix.core.actionmanagement.CoreAction.doCall(CoreAction.java:260)
	at com.mendix.core.actionmanagement.CoreAction.call(CoreAction.java:248)
	at com.mendix.core.actionmanagement.ActionManager$1.execute(ActionManager.java:168)
	at com.mendix.util.classloading.Runner.doRunUsingClassLoaderOf(Runner.java:36)
	at com.mendix.core.actionmanagement.ActionManager.executeSync(ActionManager.java:172)
	at com.mendix.core.component.InternalCore.executeSync(InternalCore.java:578)
	at com.mendix.modules.microflowengine.actions.SubMicroflowAction.execute(SubMicroflowAction.scala:43)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowObject.execute(MicroflowObject.java:47)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.executeAfterBreakingIfNecessary(MicroflowImpl.java:192)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.executeAction(MicroflowImpl.java:149)
	at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:49)
	at com.mendix.core.actionmanagement.CoreAction.doCall(CoreAction.java:260)
	at com.mendix.core.actionmanagement.CoreAction.call(CoreAction.java:248)
	at com.mendix.core.actionmanagement.CustomActionMonitorImpl$$anonfun$run$1.apply(CustomMonitoredAction.scala:14)
	at com.mendix.core.session.Worker$$anonfun$receive$3$$anonfun$2$$anon$1.execute(ActionDispatching.scala:161)
	at com.mendix.util.classloading.Runner.doRunUsingClassLoaderOf(Runner.java:36)
	at com.mendix.core.session.Worker$$anonfun$receive$3$$anonfun$2.apply(ActionDispatching.scala:163)
	at scala.util.Try$.apply(Try.scala:192)
	at com.mendix.core.session.Worker$$anonfun$receive$3.applyOrElse(ActionDispatching.scala:157)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:502)
	at com.mendix.core.session.Worker.aroundReceive(ActionDispatching.scala:153)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by RCatersels** [comment]
Adding the following files does solve the issue so these should be added to project:
slf4j-jdk14-1.7.22.jar
slf4j-log4j12-1.7.22.jar

Regards,
Ronald
